# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'karta.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(341, 533)
        MainWindow.setMinimumSize(QtCore.QSize(341, 533))
        MainWindow.setMaximumSize(QtCore.QSize(341, 533))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.width_1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.width_1.setGeometry(QtCore.QRect(40, 30, 121, 22))
        self.width_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.width_1.setDecimals(7)
        self.width_1.setMinimum(-90.0)
        self.width_1.setMaximum(90.0)
        self.width_1.setObjectName("width_1")
        self.long_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.long_2.setGeometry(QtCore.QRect(190, 30, 121, 22))
        self.long_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.long_2.setDecimals(7)
        self.long_2.setMinimum(-180.0)
        self.long_2.setMaximum(180.0)
        self.long_2.setObjectName("long_2")
        self.zoom = QtWidgets.QSpinBox(self.centralwidget)
        self.zoom.setGeometry(QtCore.QRect(120, 70, 101, 22))
        self.zoom.setMinimum(1)
        self.zoom.setMaximum(18)
        self.zoom.setObjectName("zoom")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(40, 120, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lupa-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon)
        self.search.setObjectName("search")
        self.map = QtWidgets.QLabel(self.centralwidget)
        self.map.setGeometry(QtCore.QRect(20, 200, 300, 300))
        self.map.setObjectName("map")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Крутая карта"))
        self.width_1.setPrefix(_translate("MainWindow", "Широта - "))
        self.long_2.setPrefix(_translate("MainWindow", "Долгота - "))
        self.zoom.setPrefix(_translate("MainWindow", "Масштаб - "))
        self.search.setText(_translate("MainWindow", "Поиск"))
        self.map.setText(_translate("MainWindow", "TextLabel"))
